first commit
rafinskipg/test-object-prototype pull request #1
Opened 2017-09-22 12:42 UTC by jaumejane90

2017-09-22 14:49 UTC, rafinskipg requested changes
Some changes on testing and indentation

2017-09-22 14:49 UTC, rafinskipg commented on src/board.js
> +	this.cellsMatrix = cellsMatrix
please use 2 spaces indentation

2017-09-22 14:49 UTC, rafinskipg commented on src/board.spec.js
> +
Add more test cases, including print. 

You can actually pass to the board.print the method that outputs strings to the console if you want to mock it (you have to mock it) :+1:

2017-09-22 14:49 UTC, rafinskipg commented on src/cell.spec.js
> +
ensure the print method works correctly

2017-09-22 14:49 UTC, rafinskipg commented on src/game.js
> +
Congratulations

2017-09-22 14:49 UTC, rafinskipg commented on src/game.spec.js
> +    game.rerender()
you are not testing this function actually.

2017-09-29 06:55 UTC, jaumejane90 commented
@rafinskipg I think i fixed all your comments! Feel free to keep discussion up! cc @sloy

2017-10-11 11:27 UTC, closed without merging